# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YHMLSDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJExtension', '~> 3.0.10'
 pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.9'
pod 'JKCategories', '~> 1.2'
pod 'SDCycleScrollView', '~> 1.65'
pod 'ReactiveCocoa', '~> 2.5'
pod 'BlocksKit', '~> 2.2.5'
  # Pods for YHMLSDemo

end
